project_name: nsc
release:
  github:
    owner: nats-io
    name: nsc
  name_template: '{{.Tag}}'
  draft: true
builds:
- main: ./main.go
  ldflags: "-X main.version={{.Tag}}"
  binary: nsc
  goos:
  - darwin
  - linux
  goarch:
  - amd64

dist: build

archive:
  wrap_in_directory: false
  name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format: zip
  files:
    - none*

checksum:
  name_template: '{{ .ProjectName }}-checksums.txt'

snapshot:
  name_template: 'dev'


