language: go
go:
#  - 1.9.x
#  - 1.10.x
  - 1.11.x

install:
  - go get github.com/nats-io/nkeys
  - go get github.com/nats-io/jwt
  - go get github.com/mattn/goveralls
  - go get github.com/wadey/gocovmerge
#  - go get -u honnef.co/go/tools/cmd/megacheck
#  - go get -u github.com/client9/misspell/cmd/misspell

before_script:
- EXCLUDE_VENDOR=$(go list ./... | grep -v "/vendor/")
- go build
- $(exit $(go fmt $EXCLUDE_VENDOR | wc -l))
- go vet $EXCLUDE_VENDOR
#- misspell -error -locale US .
#- megacheck $EXCLUDE_VENDOR

script:
- go test -i $EXCLUDE_VENDOR

after_success:

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux